---
title: "Daily Fantasy Data"
output: html_notebook
---

```{r}
library(nflscrapR)
library(rvest)
library(tidyverse)
library(here)
```

Scrape play by play data using the nflscrapR package:

```{r}
plays_2010 <- season_play_by_play(2010)
plays_2011 <- season_play_by_play(2011)
plays_2012 <- season_play_by_play(2012)
plays_2013 <- season_play_by_play(2013)
plays_2014 <- season_play_by_play(2014)
plays_2015 <- season_play_by_play(2015)
plays_2016 <- season_play_by_play(2016)
plays_2017 <- season_play_by_play(2017)
plays_2018 <- season_play_by_play(2018)

plays <- plays_2010 %>% 
    bind_rows(plays_2011) %>% 
    bind_rows(plays_2012) %>% 
    bind_rows(plays_2013) %>% 
    bind_rows(plays_2014) %>% 
    bind_rows(plays_2015) %>% 
    bind_rows(plays_2016) %>% 
    bind_rows(plays_2017) %>% 
    bind_rows(plays_2018)

write_csv(plays, here("play by play.csv"))
```

Scrape DK and Fanduel salary data:

```{r}
seasons <- seq(2011, 2018)
weeks <- seq(1, 17)
sites <- c("dk", "fd")

url <- "http://rotoguru1.com/cgi-bin/fyday.pl?week=17&year=2018&game=dk&scsv=1"

salary_data <- data.frame(week = NULL,
                          year = NULL,
                          GID = NULL,
                          player = NULL,
                          pos = NULL,
                          Team = NULL,
                          `H/A` = NULL,
                          Oppt = NULL,
                          points = NULL,
                          salary = NULL,
                          site = NULL)
numeric_columns <- c("week", "year", "GID", "points", "salary")

for (season in 1:length(seasons)) {
    for (week in 1:length(weeks)) {
        for (site in 1:length(sites)) {
            url <- paste("http://rotoguru1.com/cgi-bin/fyday.pl?week=", 
                         weeks[week], 
                         "&year=", 
                         seasons[season], 
                         "&game=", sites[site], 
                         "&scsv=1", 
                         sep = "")
            salary <- read_html(url) %>% 
                html_nodes("pre") %>% 
                html_text() %>% 
                strsplit("\n") %>% 
                unlist() %>% 
                .[. != ""]
            salary <- as.data.frame(salary) %>% 
                separate(salary, 
                         sep = "\\;",
                         into = c('week', 'year','GID','player','pos',
                                  'Team','H/A','Oppt','points','salary')) %>% 
                mutate(site = sites[site]) %>% 
                filter(week != "Week")
            #salary[, numeric_columns] <- as.numeric(unlist(salary[, numeric_columns]))
            salary_data <- salary_data %>% bind_rows(salary) 
        }
    }
}

salary_data[, numeric_columns] <- as.numeric(unlist(salary_data[, numeric_columns]))

write_csv(salary_data, here("salary_data.csv"))
```

```{r}
teams <- c("ARI", "ATL", "BAL", "BUF", "CAR", "CHI", "CIN", "CLE", "DAL", "DEN", "DET", "GB", "HOU", "IND", "JAC", "JAX",
           "KC", "LA", "LAC", "MIA", "MIN", "NE", "NO", "NYG", "NYJ", "OAK", "PHI", "PIT", "SD", "SEA", "SF", "STL", "TB", "TEN",
           "WAS")

players <- data.frame(Season = NULL,
                      Player = NULL,
                      Team = NULL,
                      Position = NULL,
                      name = NULL,
                      GSIS_ID = NULL)

for (season in 1:length(seasons)) {
    season_players <- season_rosters(season = seasons[season], teams = teams)
    players <- players %>% bind_rows(season_players)
}

players2 <- players %>% 
    select(Player, Team, GSIS_ID) %>% 
    unique() %>% 
    filter(Player == "Ty Montgomery")
```









